//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente_SW_Sudoku.GestorJuegos_Web {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDificultad", Namespace="http://schemas.datacontract.org/2004/07/GestorJuegos_Web")]
    public enum TipoDificultad : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VACIO = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MUY_FACIL = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FACIL = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MEDIA = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DIFICIL = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MUY_DIFICIL = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GestorJuegos_Web.IServicioJuegos")]
    public interface IServicioJuegos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/NuevoJuego", ReplyAction="http://tempuri.org/IServicioJuegos/NuevoJuegoResponse")]
        int NuevoJuego(Cliente_SW_Sudoku.GestorJuegos_Web.TipoDificultad pDifi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/NuevoJuego", ReplyAction="http://tempuri.org/IServicioJuegos/NuevoJuegoResponse")]
        System.Threading.Tasks.Task<int> NuevoJuegoAsync(Cliente_SW_Sudoku.GestorJuegos_Web.TipoDificultad pDifi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/BorrarJuego", ReplyAction="http://tempuri.org/IServicioJuegos/BorrarJuegoResponse")]
        bool BorrarJuego(int pCodJuego);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/BorrarJuego", ReplyAction="http://tempuri.org/IServicioJuegos/BorrarJuegoResponse")]
        System.Threading.Tasks.Task<bool> BorrarJuegoAsync(int pCodJuego);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/PonerValor", ReplyAction="http://tempuri.org/IServicioJuegos/PonerValorResponse")]
        bool PonerValor(int pCodJuego, int pFila, int pColumna, char pValor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/PonerValor", ReplyAction="http://tempuri.org/IServicioJuegos/PonerValorResponse")]
        System.Threading.Tasks.Task<bool> PonerValorAsync(int pCodJuego, int pFila, int pColumna, char pValor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/ObtenerValor", ReplyAction="http://tempuri.org/IServicioJuegos/ObtenerValorResponse")]
        char ObtenerValor(int pCodJuego, int pFila, int pColumna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/ObtenerValor", ReplyAction="http://tempuri.org/IServicioJuegos/ObtenerValorResponse")]
        System.Threading.Tasks.Task<char> ObtenerValorAsync(int pCodJuego, int pFila, int pColumna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/ComprobarValor", ReplyAction="http://tempuri.org/IServicioJuegos/ComprobarValorResponse")]
        bool ComprobarValor(int pCodJuego, int pFila, int pColumna, char pValor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/ComprobarValor", ReplyAction="http://tempuri.org/IServicioJuegos/ComprobarValorResponse")]
        System.Threading.Tasks.Task<bool> ComprobarValorAsync(int pCodJuego, int pFila, int pColumna, char pValor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/NumeroHuecos", ReplyAction="http://tempuri.org/IServicioJuegos/NumeroHuecosResponse")]
        int NumeroHuecos(int pCodJuego);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/NumeroHuecos", ReplyAction="http://tempuri.org/IServicioJuegos/NumeroHuecosResponse")]
        System.Threading.Tasks.Task<int> NumeroHuecosAsync(int pCodJuego);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/Ayuda", ReplyAction="http://tempuri.org/IServicioJuegos/AyudaResponse")]
        string Ayuda(int pCodJuego, int pFila, int pColumna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/Ayuda", ReplyAction="http://tempuri.org/IServicioJuegos/AyudaResponse")]
        System.Threading.Tasks.Task<string> AyudaAsync(int pCodJuego, int pFila, int pColumna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/Correcto", ReplyAction="http://tempuri.org/IServicioJuegos/CorrectoResponse")]
        bool Correcto(int pCodJuego);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/Correcto", ReplyAction="http://tempuri.org/IServicioJuegos/CorrectoResponse")]
        System.Threading.Tasks.Task<bool> CorrectoAsync(int pCodJuego);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/GetSudoku", ReplyAction="http://tempuri.org/IServicioJuegos/GetSudokuResponse")]
        string GetSudoku(int pCodJuego);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/GetSudoku", ReplyAction="http://tempuri.org/IServicioJuegos/GetSudokuResponse")]
        System.Threading.Tasks.Task<string> GetSudokuAsync(int pCodJuego);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioJuegosChannel : Cliente_SW_Sudoku.GestorJuegos_Web.IServicioJuegos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioJuegosClient : System.ServiceModel.ClientBase<Cliente_SW_Sudoku.GestorJuegos_Web.IServicioJuegos>, Cliente_SW_Sudoku.GestorJuegos_Web.IServicioJuegos {
        
        public ServicioJuegosClient() {
        }
        
        public ServicioJuegosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioJuegosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioJuegosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioJuegosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int NuevoJuego(Cliente_SW_Sudoku.GestorJuegos_Web.TipoDificultad pDifi) {
            return base.Channel.NuevoJuego(pDifi);
        }
        
        public System.Threading.Tasks.Task<int> NuevoJuegoAsync(Cliente_SW_Sudoku.GestorJuegos_Web.TipoDificultad pDifi) {
            return base.Channel.NuevoJuegoAsync(pDifi);
        }
        
        public bool BorrarJuego(int pCodJuego) {
            return base.Channel.BorrarJuego(pCodJuego);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarJuegoAsync(int pCodJuego) {
            return base.Channel.BorrarJuegoAsync(pCodJuego);
        }
        
        public bool PonerValor(int pCodJuego, int pFila, int pColumna, char pValor) {
            return base.Channel.PonerValor(pCodJuego, pFila, pColumna, pValor);
        }
        
        public System.Threading.Tasks.Task<bool> PonerValorAsync(int pCodJuego, int pFila, int pColumna, char pValor) {
            return base.Channel.PonerValorAsync(pCodJuego, pFila, pColumna, pValor);
        }
        
        public char ObtenerValor(int pCodJuego, int pFila, int pColumna) {
            return base.Channel.ObtenerValor(pCodJuego, pFila, pColumna);
        }
        
        public System.Threading.Tasks.Task<char> ObtenerValorAsync(int pCodJuego, int pFila, int pColumna) {
            return base.Channel.ObtenerValorAsync(pCodJuego, pFila, pColumna);
        }
        
        public bool ComprobarValor(int pCodJuego, int pFila, int pColumna, char pValor) {
            return base.Channel.ComprobarValor(pCodJuego, pFila, pColumna, pValor);
        }
        
        public System.Threading.Tasks.Task<bool> ComprobarValorAsync(int pCodJuego, int pFila, int pColumna, char pValor) {
            return base.Channel.ComprobarValorAsync(pCodJuego, pFila, pColumna, pValor);
        }
        
        public int NumeroHuecos(int pCodJuego) {
            return base.Channel.NumeroHuecos(pCodJuego);
        }
        
        public System.Threading.Tasks.Task<int> NumeroHuecosAsync(int pCodJuego) {
            return base.Channel.NumeroHuecosAsync(pCodJuego);
        }
        
        public string Ayuda(int pCodJuego, int pFila, int pColumna) {
            return base.Channel.Ayuda(pCodJuego, pFila, pColumna);
        }
        
        public System.Threading.Tasks.Task<string> AyudaAsync(int pCodJuego, int pFila, int pColumna) {
            return base.Channel.AyudaAsync(pCodJuego, pFila, pColumna);
        }
        
        public bool Correcto(int pCodJuego) {
            return base.Channel.Correcto(pCodJuego);
        }
        
        public System.Threading.Tasks.Task<bool> CorrectoAsync(int pCodJuego) {
            return base.Channel.CorrectoAsync(pCodJuego);
        }
        
        public string GetSudoku(int pCodJuego) {
            return base.Channel.GetSudoku(pCodJuego);
        }
        
        public System.Threading.Tasks.Task<string> GetSudokuAsync(int pCodJuego) {
            return base.Channel.GetSudokuAsync(pCodJuego);
        }
    }
}
