/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica_3_pcd;

/**
 *
 * @author ismae
 */
public class ColaFrame extends java.awt.Frame {

    /**
     * Creates new form FrameCola
     */
    public ColaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        add(jButtonSalir, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    public static void main(String[] args) throws Exception{
        
        int alto = 450, ancho = 600;
        ColaFrame frame = new ColaFrame();
        CanvasCola cv = new CanvasCola(ancho, alto, 4);
        
        frame.setVisible(true);
        frame.setLocation(650, 250);
        frame.setSize(ancho, alto);
        frame.setTitle("Practica 3 - Uso de cola visualizada con Canvas");
        frame.add(cv);
        
        
        
        ColaLenta cola = new ColaLenta(4, cv);
        
        Productor prod = new Productor(cola);
        Consumidor cons = new Consumidor(cola);
        Thread t1 = new Thread(cons); //Transformamos el runneable consumidor en thread
        
        prod.start();    
        t1.start();
        
        prod.join();
        t1.join();
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalir;
    // End of variables declaration//GEN-END:variables
}
