/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "GestorJuegos.h"

//MENU PRINCIPAL DEL SUDOKU
int MenuPrincipal(bool_t pInicio)
{
    int valor;

    if (pInicio)
    {
        printf("1.- Juego Nuevo\n");
        printf("2.- -----------\n");
        printf("3.- -----------\n");
        printf("4.- -----------\n");
        printf("5.- -----------\n");
    }
    else
    {
        printf("1.- -----------\n");
        printf("2.- Borrar Juego\n");
        printf("3.- Poner Valor\n");
        printf("4.- Borrar Valor\n");
        printf("5.- Ayuda\n");
    }
    printf("6.- Salir\n");
    printf("Elige Opción: ");
    scanf("%d", &valor);

    return valor;
}

//MENU DE ELECCION DE LA DIFICULTAD DEL SUDOKU
TDificultad MenuDificultad()
{
    int valor;
    do
    {
        printf("Eligen la Dificultad:\n");
        printf("Muy Fácil(1) Fácil(2) Medio(3) Difícil(4) Muy Difícil(5)\n");
        printf("Elige Opción: ");
        scanf("%d", &valor);
        if (valor<1 || valor>5)
            printf("** Error, elija una dificultad correcta.\n");
    }
    while(valor<1 || valor>5);
    return (TDificultad)valor;
}


// MAIN
int
main (int argc, char *argv[])
{
    char *host;
    int CodSudoActual;
    bool_t Inicio = TRUE;

    if (argc != 3){
    	CodSudoActual = 0;
    }
    else
    {
    	CodSudoActual = atoi(argv[2]);
    	Inicio = FALSE;
    }
    host = argv[1];
    
    
    CLIENT *clnt;
    
    int Menu;
    TDificultad MenuDif;
    
    int F, C, Aviso = 0;
    char V;
    Cadena sn;
    RCadena *SudoActual, *help;
    
     //Codigo del sudoku que el cliente esta jugando
    int *CodSudoEnEjecucion;
    int *NHuecosRestantes;
    TFCV tfcv;
    TFC tfc;
    char *ValorEncontrado;
    bool_t *Sudoku_OK = FALSE;
    bool_t *OK = FALSE;
    
    clnt = clnt_create (host, GESTORJUEGOS, GESTORJUEGOS_VER, "tcp");
    if (clnt == NULL){
    	clnt_pcreateerror (host);
	exit (1);
    }
    
    do
    {
        system("clear");
    	SudoActual = getsudoku_1(&CodSudoActual, clnt);
	if (SudoActual == (RCadena *) NULL) {
		clnt_perror (clnt, "ERROR en la llamada GetSudoku()");
	}
	else
	{
		printf("%s", SudoActual->Contenido);
	}
	
	//Control de Avisos al escribir valores erroneos o pedir Ayuda
	if (Aviso>0)
        {
            printf("*** ");
            switch (Aviso)
            {
            case 1:
                printf("La opción %d no está en el menú.", Menu);
                break;
            case 2:
                printf("La posición F=%d C=%d introducida es incorrecta.", F, C);
                break;
            case 3:
                printf("La posición F=%d C=%d está ocupada", F, C);
                break;
            case 4:
                printf("El valor '%c' no se puede poner en la posición F=%d C=%d", V, F, C);
                break;
            case 5:
                printf("El valor '%c' es incorrecto para el juego", V);
                break;
            case 6:
                printf("Los posibles valores en la posición F=%d C=%d son: %s", F, C, help->Contenido);
                break;
            }
            printf(" ***\n");
            Aviso=0;
        }
        
        NHuecosRestantes = numerohuecos_1(&CodSudoActual, clnt);
	if (NHuecosRestantes == (int *) NULL) {
		clnt_perror (clnt, "ERROR en la llamada numeroHuecos()");
	}
	else{
		if (*NHuecosRestantes == 0)
        	{
            		printf("*** SUDOKU COMPLETO ");
            		
            		Sudoku_OK = correcto_1(&CodSudoActual, clnt);
			if (Sudoku_OK == (bool_t *) NULL) {
				clnt_perror (clnt, "ERROR en la llamada correcto()");
			}
            		else{
            			if (*Sudoku_OK == FALSE)
                		    printf("PERO IN");
            			printf("CORRECTO ***\n");
            		}
            		
        	}
	}
	
	printf("\n");
	
	Menu=MenuPrincipal(Inicio);
	switch(Menu)
	{
	    case 1:
	    	if(Inicio == TRUE){
	    		system("clear");
	    		MenuDif = MenuDificultad();
	    		printf("La dificultad elegida es: %d\n", MenuDif);
	    		CodSudoEnEjecucion = nuevo_1(&MenuDif, clnt);
			if (CodSudoEnEjecucion == (int *) NULL) {
				clnt_perror (clnt, "ERROR en la llamada nuevo()");
			}
			else{
				CodSudoActual = *CodSudoEnEjecucion;
				Inicio = FALSE;
			}
	    	}
	    	else Aviso = 1;
	        break;
	        
	    case 2:
	    	if (Inicio==FALSE)
            	{
                	printf("¿ Está seguro de borrar el juego ? (s/n): ");
                	scanf("%s", &sn[0]);
                	if (sn[0]=='s' || sn[0]=='S')
                	{
                    	    OK = borrar_1(&CodSudoActual, clnt);
			    if (OK == (bool_t *) NULL) {
				clnt_perror (clnt, "ERROR en la llamada Borrar()");
			    }
                    	    else{
                    	    	Inicio=TRUE;
                    	    	CodSudoActual = 0;
                    	    }
                	}
            	}
            	else Aviso=1;
            	break;
            	
            case 3: //Poner Valor
            	if (Inicio==FALSE)
            	{
                	printf("Introduce Fila, Columna y Valor: ");
                	scanf("%d %d %c", &F, &C, &V);
                	
                	tfc.pCod = CodSudoActual;
                	tfc.pFil = F-1;
                	tfc.pCol = C-1;
                    		
                    	ValorEncontrado = obtenervalor_1(&tfc, clnt);
			if (ValorEncontrado == (char *) NULL) {
			    clnt_perror (clnt, "ERROR en la llamada ObtenerValor()");
			}
			else
			{
			    if (V<'1' || V>'9')
                    	        Aviso=5; //Valor incorrecto
			
			    else if(*ValorEncontrado != ' ')
			    	Aviso = 3; //Posicion ocupada
                    	        
                	    else if (F<1 || F>9 || C<1 || C>9 )
                    	        Aviso=2; //F y C incorrectos
                    	        
			    else
			    {
			    	tfcv.pCod = CodSudoActual;
			    	tfcv.pFil = F-1;
			    	tfcv.pCol = C-1;
			    	tfcv.pVal = V;
			    	OK = ponervalor_1(&tfcv, clnt);
				if (OK == (bool_t *) NULL) {
				    clnt_perror (clnt, "ERROR en la llamada PonerValor()");
				}
				else
				{
				    OK = comprobarvalor_1(&tfcv, clnt);
				    if (OK == (bool_t *) NULL) {
					clnt_perror (clnt, "ERROR en la llamada ComprobarValor()");
				    }
				    else
				    {
				    	
				    	if(OK == FALSE){
				    	    Aviso = 4;
				    	    printf("Llegaste al if");
				    	}
				    	else{
				    	    Aviso = 0;
				    	}
				    }
				}
			    }
			}
            	}
            	else Aviso=1;
            	break;
            	
            case 4: //Borrar Valor
            	if (Inicio==FALSE)
            	{
                	printf("Introduce Fila, y Columna: ");
                	scanf("%d %d", &F, &C);
                	if (F<1 || F>9 || C<1 || C>9 )
                    	    Aviso=2;
               	else
               	{
               	    tfcv.pCod = CodSudoActual;
               	    tfcv.pFil = F-1;
               	    tfcv.pCol = C-1;
               	    tfcv.pVal = ' ';
               	    
               	    OK = ponervalor_1(&tfcv, clnt);
			    if (OK == (bool_t *) NULL) {
				clnt_perror (clnt, "ERROR en la llamada PonerValor()");
			    }
               	}
            	}
            	else Aviso=1;
            	break;
            	
            case 5: //Ayuda
                if (Inicio==FALSE)
            	 {
                     printf("Introduce Fila y Columna a obtener ayuda: ");
                     scanf("%d %d", &F, &C);
                     
                     tfc.pCod = CodSudoActual;
                     tfc.pFil = F-1;
                     tfc.pCol = C-1;
                     
                     ValorEncontrado = obtenervalor_1(&tfc, clnt);
		      if (ValorEncontrado == (char *) NULL) {
	                  clnt_perror (clnt, "ERROR en la llamada ObtenerValor()");
		      }
		      else
		      {
		      	 if (F<1 || F>9 || C<1 || C>9 || *ValorEncontrado != ' ')
                            Aviso=2; //Posicion incorrecta
                     	 else
                     	 {
                     	     help = ayuda_1(&tfc, clnt);
			     if (help == (RCadena *) NULL) {
				clnt_perror (clnt, "ERROR en la llamada Error()");
			     }
			     else
			     {
			     	Aviso=6;
			     } 
                     	 }
		      }
            	 }
            	 else Aviso=1;
            	 break;
            	
            case 6: //Salir
            	printf("\n** Si quieres continuar con el Sudoku anterior, no olvides que su codigo es %d \n\n", CodSudoActual);
                break;
                
            default:
                Aviso = 1;
	}
	
    }while(Menu != 6);
    
    
    clnt_destroy (clnt);
    exit (0);
}






