/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "GestorJuegos.h"

bool_t
xdr_Cadena (XDR *xdrs, Cadena objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, 300,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDificultad (XDR *xdrs, TDificultad *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RCadena (XDR *xdrs, RCadena *objp)
{
	register int32_t *buf;

	 if (!xdr_bool (xdrs, &objp->Salida))
		 return FALSE;
	 if (!xdr_Cadena (xdrs, objp->Contenido))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TFCV (XDR *xdrs, TFCV *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->pCod))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->pFil))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->pCol))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->pCod);
		IXDR_PUT_LONG(buf, objp->pFil);
		IXDR_PUT_LONG(buf, objp->pCol);
		}
		 if (!xdr_char (xdrs, &objp->pVal))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->pCod))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->pFil))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->pCol))
				 return FALSE;

		} else {
		objp->pCod = IXDR_GET_LONG(buf);
		objp->pFil = IXDR_GET_LONG(buf);
		objp->pCol = IXDR_GET_LONG(buf);
		}
		 if (!xdr_char (xdrs, &objp->pVal))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->pCod))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pFil))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pCol))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->pVal))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TFC (XDR *xdrs, TFC *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->pCod))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pFil))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pCol))
		 return FALSE;
	return TRUE;
}
