/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "GestorJuegos.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
gestorjuegos_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		TDificultad nuevo_1_arg;
		int borrar_1_arg;
		TFCV ponervalor_1_arg;
		TFC obtenervalor_1_arg;
		TFCV comprobarvalor_1_arg;
		int numerohuecos_1_arg;
		int correcto_1_arg;
		TFC ayuda_1_arg;
		int getsudoku_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case Nuevo:
		_xdr_argument = (xdrproc_t) xdr_TDificultad;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) nuevo_1_svc;
		break;

	case Borrar:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) borrar_1_svc;
		break;

	case PonerValor:
		_xdr_argument = (xdrproc_t) xdr_TFCV;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) ponervalor_1_svc;
		break;

	case ObtenerValor:
		_xdr_argument = (xdrproc_t) xdr_TFC;
		_xdr_result = (xdrproc_t) xdr_char;
		local = (char *(*)(char *, struct svc_req *)) obtenervalor_1_svc;
		break;

	case ComprobarValor:
		_xdr_argument = (xdrproc_t) xdr_TFCV;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) comprobarvalor_1_svc;
		break;

	case NumeroHuecos:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) numerohuecos_1_svc;
		break;

	case Correcto:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) correcto_1_svc;
		break;

	case Ayuda:
		_xdr_argument = (xdrproc_t) xdr_TFC;
		_xdr_result = (xdrproc_t) xdr_RCadena;
		local = (char *(*)(char *, struct svc_req *)) ayuda_1_svc;
		break;

	case GetSudoku:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_RCadena;
		local = (char *(*)(char *, struct svc_req *)) getsudoku_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (GESTORJUEGOS, GESTORJUEGOS_VER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, GESTORJUEGOS, GESTORJUEGOS_VER, gestorjuegos_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (GESTORJUEGOS, GESTORJUEGOS_VER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, GESTORJUEGOS, GESTORJUEGOS_VER, gestorjuegos_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (GESTORJUEGOS, GESTORJUEGOS_VER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
