/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica_7_pcd;

import java.util.Random;

/**
 *
 * @author ismae
 */
public class Generador extends java.awt.Frame {

    /**
     * Creates new form Generador
     */
    public Generador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        
        int nVehiculos = 3; //numero de vehiculos que se crearan
        int alto = 550, ancho = 800;
        
        Generador frame = new Generador();
        CanvasTunel cv = new CanvasTunel(ancho, alto, nVehiculos);
        
        Random random = new Random();
        random.setSeed(System.currentTimeMillis());
        
        frame.setVisible(true);
        frame.setLocation(550, 200);
        frame.setSize(ancho, alto);
        frame.setTitle("Practica 5 - Tunel de lavado de vehículos");
        frame.add(cv);
        
        Tunel tunel = new Tunel(cv);
        Thread vehiculos[] = new Thread[nVehiculos];
        
        //===== Creacion de los vehiculos =====
        for (int i = 0; i < nVehiculos; i++) {
            Thread.sleep((random.nextInt(3) + 1) * 1000); //Espera un tiempo antes de crear el siguiente vehículo para no colapsar
            
            if (random.nextInt(10) < 5) { //Disminuir el valor para aumentar la probabilidad de que se generen furgos 
                vehiculos[i] = new Coche(tunel, i);
            }
            else{
                vehiculos[i] = new Thread(new Furgo(tunel, i));
            }
            
            vehiculos[i].start();
        }
        
        for (int i = 0; i < nVehiculos; i++) {
            vehiculos[i].join();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
